### ISSUE TITLE
error: Connection to klpbbs.com timed out

### ISSUE THREAD

**Issue by LFTOOO** [xyz8848/KLPBBS_auto_sign_in#5]
<img width="1028" alt="image" src="https://github.com/xyz8848/KLPBBS_auto_sign_in/assets/136160386/be25868e-51ee-4bc2-a220-feeb0121cab2">

**Comment by xyz8848** [comment]
在近期访问论坛时，偶尔也会出现这样的页面：
![image](https://github.com/xyz8848/KLPBBS_auto_sign_in/assets/71914524/fc66f1a0-4d9e-4454-8007-cce2dda82c5b)

这似乎是由于苦力怕论坛近期受到了网络攻击，禁止了部分地区的IP导致的

**Comment by LFTOOO** [comment]
这是否有解决办法？

**Comment by xyz8848** [comment]
> 这是否有解决办法？

 暂时没有，只能手动签到

**Comment by xyz8848** [comment]
2024年4月10日 苦力怕论坛解除了对部分地区的IP封禁，现在脚本可以正常签到
